### ISSUE TITLE
Terraform "ERROR: Record does not exist (81044)"

### ISSUE THREAD

**Issue by SinLess-Games** [k8s-at-home/flux-cluster-template#355]
# Details

**Ask your question:**

So I am in the process of setting everything up using this template, and i ran into something; it may be your code; but it's most likely me. I am in the stage of setting up Terraform, But for whatever reason; even after searching through google; I get this error. 
```
sinless777@Sinless-Games-Desktop:~/Desktop/Cluster-1$ task terraform:plan
task: [terraform:plan] terraform plan 
data.sops_file.cloudflare_secrets: Reading...
data.sops_file.cloudflare_secrets: Read complete after 0s [id=-]
data.http.ipv4: Reading...
data.cloudflare_zones.domain: Reading...
data.http.ipv4: Read complete after 0s [id=http://ipv4.icanhazip.com]
data.cloudflare_zones.domain: Read complete after 0s [id=67a974a36446a1eb36e7a1755fa412f4]
cloudflare_record.ipv4: Refreshing state... [id=babc533255810d67bdf4e0f4af518660]
cloudflare_zone_settings_override.cloudflare_settings: Refreshing state... [id=80727c2755fc0be1d60b848b1315749e]
╷
│ Error: Record does not exist. (81044)
│ 
│   with cloudflare_record.ipv4,
│   on main.tf line 85, in resource "cloudflare_record" "ipv4":
│   85: resource "cloudflare_record" "ipv4" {
│ 
╵
task: Failed to run task "terraform:plan": exit status 1
```

Which after looking at the file, I notice my IDE kicks a few unresolved references, but since the error doesn't pertain to that i am not concerned . So my question is what am i doing wrong. Do i need to go to the cloudflare/cloudflare repo and file an issue or is it the script itself?

I also tried creating the records myself, and i will still get the same error. I double checked, and triple checked and i am confident my config is correct, but i seem to be unable to resolve this myself.

**Comment by onedr0p** [comment]
I have seen this issue come up when terraform loses track of what is has already configured, or there is duplicate configuration that terraform is not tracking. I would suggest deleting all the cloudflare resources that the terraform script is creating and try running it again.

**Comment by SinLess-Games** [comment]
Thank you,  Deleteing the TFstate files worked. Also i had to delete the DNS records i created so that Teraform could apply the changes.
