### ISSUE TITLE
Webhook template issue in receiver.yaml

### ISSUE THREAD

**Issue by Doonga** [k8s-at-home/flux-cluster-template#397]
I was having a problem where my github webhook was showing a 400 after a bunch of troubleshooting, I found that the values in my receiver.yaml were incorrect.

I had to make the following adjustments. Once I did this the webhook dashboard went from a red triangle to a green check.

Changed:
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      name: flux-system
      namespace: flux-system

To:
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      name: flux-cluster
      namespace: flux-system

also Changed:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      name: flux-system
      namespace: flux-system

To:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      name: flux-cluster
      namespace: flux-system

**Comment by onedr0p** [comment]
Thanks for reporting, I have update it.
