### ISSUE TITLE
Nuke command does not clear host_vars

### ISSUE THREAD

**Issue by FordMustang0288** [k8s-at-home/flux-cluster-template#399]
# Details

**What steps did you take and what happened:**

Fill in .config.env
Run steps all the way to ansible ping
Ping is a success
Nuke cluster
Change .config.env host name for say control node
Run steps all the way to ping

{"msg": "Missing sudo password"} for control node

**What did you expect to happen:**

I expected that the ping would succeed

**Additional Information:**

It is now obvious that the nuke option needs to clear out provision/ansible/inventory/host_vars

**Comment by onedr0p** [comment]
Running the configure task should replace the files with the new config, it does not clean up stale files though. There is no state on what was done before, so not sure how I can clean up the stale files. It's a manual task. If you have any ideas feel free to open a PR.
