### ISSUE TITLE
Use Dashy Dashboard in place of Hajimari

### ISSUE THREAD

**Issue by FordMustang0288** [k8s-at-home/flux-cluster-template#408]
I have personally chosen to use Dashy Dashboard as my landing page. I see that Hajimari utilizes helm and that replaced the initial use of Homer. So it is possible to use another landing page with the right know-how.

Dashy:
https://github.com/Lissy93/dashy

This looks like it would be what we need to utilize:
https://github.com/Lissy93/dashy/discussions/45#discussioncomment-897961

**Describe the solution you'd like:**

Provide optional install of Dashy Dashboard vs Hajimari

**Anything else you would like to add:**

I have not come across anything Helm related for Dashy. I'm not sure if that is a dealbreaker.

**Additional Information:**

Switch from homer to hajimari:
https://github.com/vladzaharia/template-cluster-k3s/commit/201e8eca43ad9458e8e2fa03815340cdac13c379

Initial implementation of homer:
https://github.com/k8s-at-home/flux-cluster-template/commit/3501d5a9ed789f022a4f77df7ec8d537e5d3a6a1

**Comment by onedr0p** [comment]
Hajimari works with the Kubernetes API to auto create the dashboard from ingress annotations. You are free to use whatever you like and expand your cluster in anyway you see fit but I'll not be switching this out, sorry.
