### ISSUE TITLE
How to keep up-to-date my repo?

### ISSUE THREAD

**Issue by fabricesemti80** [k8s-at-home/flux-cluster-template#437]
# Details

**Ask your question:**

What is the best way to keep my repo - the one I made from the template - up-to-date with the changes on the template?
(I think  with fork I would have the option, but not with template)

**Comment by onedr0p** [comment]
I guess it's more of "you now have the tools you need to go at it and do your own things".

But you can use git to cherry pick commits

https://github.com/k8s-at-home/flux-cluster-template/wiki#keep-your-repository-up-to-date-with-this-template

**Comment by fabricesemti80** [comment]
Thanks. I will do that.
